version: '2.0'

services:
  # web:
  #   build: .
  #   ports:
  #     - "3030:3030"
  #   links:
  #     - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "rageagain"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "web"
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '53306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./data/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

volumes:
  db-data: