name = "rageagain-dev"
type = "webpack"
account_id = "3182c92fb67a3893aa91d143bc6c8e57"
workers_dev = true
webpack_config = "webpack.config.js"
kv_namespaces = [
    { binding = "YOUTUBE_REQUESTS", id = "be42270946734636abc4a21e210a20ba", preview_id = "be42270946734636abc4a21e210a20ba" }
]

[env.production]
name = "rageagain"