name = "rageagain-dev"
type = "webpack"
account_id = "3182c92fb67a3893aa91d143bc6c8e57"
workers_dev = true
webpack_config = "webpack.config.js"
kv_namespaces = [
    { binding = "YOUTUBE_REQUESTS", id = "be42270946734636abc4a21e210a20ba", preview_id = "be42270946734636abc4a21e210a20ba" },
    { binding = "GITHUB_DATA", id = "161674bec31e4ca193f3717ae27f491d", preview_id = "161674bec31e4ca193f3717ae27f491d" }
]

[env.production]
name = "rageagain"
kv_namespaces = [
    { binding = "YOUTUBE_REQUESTS", id = "59fe223a01f04d649649211ab4869fc4" },
    { binding = "GITHUB_DATA", id = "161674bec31e4ca193f3717ae27f491d" }
]