name: Build Server

on:
  push:
    branches: [ master ]
    paths:
    - '**.rs'
  pull_request:
    branches: [ master ]
    paths:
    - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd server && cargo build --verbose
    - name: Run tests
      run: cd server && cargo test --verbose
